### ISSUE TITLE
fs-extra needs to be a dependency

### ISSUE THREAD

**Issue by michael-brade** [bartosz-m/livescript-esm-loader#2]
It is not enough to have `fs-extra` just as a `devDependency`, even if the `livescript-esm-loader` is itself only used as a `devDependency`. I had to add `fs-extra` to my project to get it to work in the meantime.

**Comment by bartosz-m** [comment]
Thanks for info, I've updated `package.json`

**Comment by michael-brade** [comment]
great, it works, so I guess we can close this :)
